config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index'
  
  match '/invoices/result/', to: 'invoices#result', as: :result_invoice, via: :get
  match '/invoices/analysis/', to: 'invoices#analysis', as: :analysis_invoice, via: :get
  match '/pages', to: 'pages#index', as: :pages, via: :get

  resources :invoices

  
  
  # get '/invoices/result', to: "invoices#result", as: :result_invoice
  # root to: 'invoices#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  self.primary_key = 'customer_id'
  has_many :invoices, primary_key: :customer_id
  validates :customer_id, uniqueness: true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  # self.primary_key = 'invoice_id' #can't be primary as not unique
  belongs_to :customer, class_name: 'Customer', foreign_key: 'customer_id'

  # scope :by_customer, ->(customer_id) { where("customer_id = ?", customer_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :site_search

  # def site_search
  #   @q = Invoice.ransack(params[:q])
  #   @result = @q.result
  # end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :analysis, :index]

  def index
    @q = Invoice.ransack(params[:q])
    @result = @q.result
    # @invoices = Invoice.select(:invoice_id, :customer_id, :order_id, :sales_person_id, :invoice_date).group(:invoice_id, :customer_id, :order_id, :sales_person_id, :invoice_date).limit(6)
  end

  def show
  end

  def analysis
# byebug
#     @q = Invoice.ransack(params[:q])
# # byebug
#     @result = @q.result
    # redirect_to analysis_invoice_url

    # @customer_id = 'COM002'
    # sales = []
    # 12.times.each{|i| sales << 0}
    # i = Invoice.where(customer_id: @customer_id).limit(200)
    # i.each { |record| sales[record.fiscal_month] += record.invoice_price } 
    # @result = sales
    # @total = @result.each.sum
  end

  def result
    # @data = Daru::Dataframe.from_activerecord(@invoices, )
    @data_frame = Daru::DataFrame.from_activerecord(Invoice.last(50))
  end

  def new
    @invoice = Invoice.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.where(:invoice_id => params[:id])
      # @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:customer_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @q = Invoice.ransack(params[:q])
    @result = @q.result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice, local: true) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/analysis.html.erb
<div class="container">
  <h1>Sales</h1>

  <div id="msgid"></div>

  <div class="search_form">
    <%= search_form_for @q do |f| %>
      <%= f.label :customer_id_cont, "Cusomter Id contains: " %>
      <%= f.search_field :customer_id_cont %>
      <%= f.submit %>
    <% end %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Customer Id</th>
        <th>1</th>
        <th>2</th>
        <th>3</th>
        <th>4</th>
        <th>5</th>
        <th>6</th>
        <th>7</th>
        <th>8</th>
        <th>9</th>
        <th>10</th>
        <th>11</th>
        <th>12</th>
        <th>Total</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><%=@customer_id%></td>
        <% @result.each do |revenue| %>
        <td><%= revenue %></td>
        <% end %>
        <td><%= @total %></td>
      </tr>
    </tbody>
  </table>

</div>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Invoices</h1>

  <div id="msgid"></div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Invoice</th>
        <th>Customer ID</th>
        <th>Customer Name</th>
        <th>Order</th>
        <th>Sales Rep</th>
        <th>Invoice Date</th>
      </tr>
    </thead>

    <tbody>
      <% @result.each do |invoice| %>
      <tr>
        <td><%= link_to invoice.invoice_id, :action => :show, :id => invoice.invoice_id %></td>
        <td><%= invoice.customer_id %></td>
        <td><%= invoice.customer.customer_name %></td>
        <td><%= invoice.order_id %></td>
        <td><%= invoice.sales_person_id %></td>
        <td><%= invoice.invoice_date %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/invoices/result.html.erb
<h1>Test</h1>
<%=raw @data_frame.data %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<div class=container>
<strong>Invoice Number: </strong><%= @invoice.first.invoice_id %><br>
<strong>Customer ID: </strong><%= @invoice.first.customer_id %><br>
<strong>Customer Name: </strong><%= @invoice.first.customer.customer_name %><br>
<strong>Order Number: </strong><%= @invoice.first.order_id %><br>
<strong>Sales Person: </strong><%= @invoice.first.sales_person_id %><br>
<strong>Invoice Date: </strong><%= @invoice.first.invoice_date.strftime("%e %B %Y") %><br>
<br>
<table class="table table-striped">
  <head>
    <tr>
      <th>Item</th>
      <th>Order Qty</th>
      <th>Backorder Qty</th>
      <th>Shipped Qty</th>
      <th>Unit Price</th>
      <th>Total Price</th>
    </tr>
  </head>
  <tbody>
    <% @invoice.each do |invoice| %>
    <tr>
      <td><%= invoice.item_id %></td>
      <td><%= invoice.order_qty %></td>
      <td><%= invoice.backorder_qty %></td>
      <td><%= invoice.shipped_qty %></td>
      <td><%= number_to_currency(invoice.unit_price) %></td>
      <td><%= number_to_currency(invoice.invoice_price) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<%= link_to 'Back', invoices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PenPac</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "shared/nav" %>
    
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <h1>Index Page</h1>

  <div class="search_form">
    <%= search_form_for @q do |f| %>
    <%= f.label :customer_id_cont, "Cusomter Id contains: " %>
    <%= f.search_field :customer_id_cont %>
    <%= f.label :fiscal_year_eq, "Fiscal year: " %>
    <%= f.search_field :fiscal_year_eq %>
    <%= f.label :fiscal_month_eq, "Fiscal year: " %>
    <%= f.search_field :fiscal_month_eq %>
    <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Pentel BI</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sales', invoices_path, class: 'nav-link' %>
        <!-- <a class="nav-link" href="#">Sales</a> -->
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>